//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Group7_demo_PLL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_Group7_demo_PLL.Resource.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Category_BackButton {
            get {
                return ResourceManager.GetString("Category.BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Category_DeleteButton {
            get {
                return ResourceManager.GetString("Category.DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string Category_Details_Title {
            get {
                return ResourceManager.GetString("Category.Details.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Category_DetailsButton {
            get {
                return ResourceManager.GetString("Category.DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Category_EditButton {
            get {
                return ResourceManager.GetString("Category.EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products in this category..
        /// </summary>
        public static string Category_NoProducts {
            get {
                return ResourceManager.GetString("Category.NoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Category_ProductCount {
            get {
                return ResourceManager.GetString("Category.ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products:.
        /// </summary>
        public static string Category_ProductsLabel {
            get {
                return ResourceManager.GetString("Category.ProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to finalize order..
        /// </summary>
        public static string FinalizeOrderError {
            get {
                return ResourceManager.GetString("FinalizeOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been finalized successfully!.
        /// </summary>
        public static string FinalizeOrderSuccess {
            get {
                return ResourceManager.GetString("FinalizeOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string GetAll_Contains {
            get {
                return ResourceManager.GetString("GetAll.Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GetAll_Delete {
            get {
                return ResourceManager.GetString("GetAll.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string GetAll_Details {
            get {
                return ResourceManager.GetString("GetAll.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GetAll_Edit {
            get {
                return ResourceManager.GetString("GetAll.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Our Categories.
        /// </summary>
        public static string GetAll_Header {
            get {
                return ResourceManager.GetString("GetAll.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found..
        /// </summary>
        public static string GetAll_NoCategories {
            get {
                return ResourceManager.GetString("GetAll.NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string GetAll_Products {
            get {
                return ResourceManager.GetString("GetAll.Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover a variety of products organized by category..
        /// </summary>
        public static string GetAll_SubHeader {
            get {
                return ResourceManager.GetString("GetAll.SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string GetAll_Title {
            get {
                return ResourceManager.GetString("GetAll.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Products.
        /// </summary>
        public static string GetAll_ViewProducts {
            get {
                return ResourceManager.GetString("GetAll.ViewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_EmailLabel {
            get {
                return ResourceManager.GetString("Login.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login_Header {
            get {
                return ResourceManager.GetString("Login.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_PasswordLabel {
            get {
                return ResourceManager.GetString("Login.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to perform this action..
        /// </summary>
        public static string LoginRequiredError {
            get {
                return ResourceManager.GetString("LoginRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string newLayout_About {
            get {
                return ResourceManager.GetString("newLayout.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string newLayout_AllProducts {
            get {
                return ResourceManager.GetString("newLayout.AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string newLayout_Categories {
            get {
                return ResourceManager.GetString("newLayout.Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string newLayout_Home {
            get {
                return ResourceManager.GetString("newLayout.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string newLayout_Login {
            get {
                return ResourceManager.GetString("newLayout.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string newLayout_Logout {
            get {
                return ResourceManager.GetString("newLayout.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string newLayout_MyProfile {
            get {
                return ResourceManager.GetString("newLayout.MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Shop.
        /// </summary>
        public static string newLayout_NavbarBrand {
            get {
                return ResourceManager.GetString("newLayout.NavbarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrivals.
        /// </summary>
        public static string newLayout_NewArrivals {
            get {
                return ResourceManager.GetString("newLayout.NewArrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Items.
        /// </summary>
        public static string newLayout_PopularItems {
            get {
                return ResourceManager.GetString("newLayout.PopularItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string newLayout_SearchButton {
            get {
                return ResourceManager.GetString("newLayout.SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search products....
        /// </summary>
        public static string newLayout_SearchPlaceholder {
            get {
                return ResourceManager.GetString("newLayout.SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string newLayout_Shop {
            get {
                return ResourceManager.GetString("newLayout.Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string newLayout_SiteTitle {
            get {
                return ResourceManager.GetString("newLayout.SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Order.
        /// </summary>
        public static string newLayout_ViewOrder {
            get {
                return ResourceManager.GetString("newLayout.ViewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Order_ActionsColumn {
            get {
                return ResourceManager.GetString("Order.ActionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        public static string Order_ApplyChangesButton {
            get {
                return ResourceManager.GetString("Order.ApplyChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Order_BackButton {
            get {
                return ResourceManager.GetString("Order.BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Order_CancelButton {
            get {
                return ResourceManager.GetString("Order.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Order_CheckoutButton {
            get {
                return ResourceManager.GetString("Order.CheckoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Current Order.
        /// </summary>
        public static string Order_Current_Title {
            get {
                return ResourceManager.GetString("Order.Current.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Order.
        /// </summary>
        public static string Order_DeleteButton {
            get {
                return ResourceManager.GetString("Order.DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this order?.
        /// </summary>
        public static string Order_DeleteConfirm {
            get {
                return ResourceManager.GetString("Order.DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Name.
        /// </summary>
        public static string Order_DeliveryNameColumn {
            get {
                return ResourceManager.GetString("Order.DeliveryNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Your Order.
        /// </summary>
        public static string Order_Edit_Title {
            get {
                return ResourceManager.GetString("Order.Edit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Order.
        /// </summary>
        public static string Order_EditButton {
            get {
                return ResourceManager.GetString("Order.EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalized Orders.
        /// </summary>
        public static string Order_Finalized_Title {
            get {
                return ResourceManager.GetString("Order.Finalized.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalized On.
        /// </summary>
        public static string Order_FinalizedOnColumn {
            get {
                return ResourceManager.GetString("Order.FinalizedOnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Order_ImageColumn {
            get {
                return ResourceManager.GetString("Order.ImageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items.
        /// </summary>
        public static string Order_ItemCountColumn {
            get {
                return ResourceManager.GetString("Order.ItemCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items:.
        /// </summary>
        public static string Order_ItemCountLabel {
            get {
                return ResourceManager.GetString("Order.ItemCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Location.
        /// </summary>
        public static string Order_LocationColumn {
            get {
                return ResourceManager.GetString("Order.LocationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have any active orders..
        /// </summary>
        public static string Order_NoActiveOrder {
            get {
                return ResourceManager.GetString("Order.NoActiveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Order_PaymentMethodColumn {
            get {
                return ResourceManager.GetString("Order.PaymentMethodColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Order_ProductColumn {
            get {
                return ResourceManager.GetString("Order.ProductColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Order_QuantityColumn {
            get {
                return ResourceManager.GetString("Order.QuantityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Order_RemoveColumn {
            get {
                return ResourceManager.GetString("Order.RemoveColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Order_SubtotalColumn {
            get {
                return ResourceManager.GetString("Order.SubtotalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string Order_TotalPriceColumn {
            get {
                return ResourceManager.GetString("Order.TotalPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price:.
        /// </summary>
        public static string Order_TotalPriceLabel {
            get {
                return ResourceManager.GetString("Order.TotalPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Order_UnitPriceColumn {
            get {
                return ResourceManager.GetString("Order.UnitPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Order_ViewButton {
            get {
                return ResourceManager.GetString("Order.ViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with Card.
        /// </summary>
        public static string Payment_CardButton {
            get {
                return ResourceManager.GetString("Payment.CardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder&apos;s Name.
        /// </summary>
        public static string Payment_CardholderLabel {
            get {
                return ResourceManager.GetString("Payment.CardholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder&apos;s Name.
        /// </summary>
        public static string Payment_CardholderPlaceholder {
            get {
                return ResourceManager.GetString("Payment.CardholderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can only contain letters and spaces..
        /// </summary>
        public static string Payment_CardholderValidation {
            get {
                return ResourceManager.GetString("Payment.CardholderValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string Payment_CardNumberLabel {
            get {
                return ResourceManager.GetString("Payment.CardNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234 5678 9012 3457.
        /// </summary>
        public static string Payment_CardNumberPlaceholder {
            get {
                return ResourceManager.GetString("Payment.CardNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a 16-digit card number in the format: 1234 5678 9012 3456.
        /// </summary>
        public static string Payment_CardNumberValidation {
            get {
                return ResourceManager.GetString("Payment.CardNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with Cash.
        /// </summary>
        public static string Payment_CashButton {
            get {
                return ResourceManager.GetString("Payment.CashButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select how you’d like to pay for your order..
        /// </summary>
        public static string Payment_ChooseDescription {
            get {
                return ResourceManager.GetString("Payment.ChooseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Payment Method.
        /// </summary>
        public static string Payment_ChooseTitle {
            get {
                return ResourceManager.GetString("Payment.ChooseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string Payment_CVVLabel {
            get {
                return ResourceManager.GetString("Payment.CVVLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV must be exactly 3 digits..
        /// </summary>
        public static string Payment_CVVValidation {
            get {
                return ResourceManager.GetString("Payment.CVVValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string Payment_ExpirationLabel {
            get {
                return ResourceManager.GetString("Payment.ExpirationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/YYYY.
        /// </summary>
        public static string Payment_ExpirationPlaceholder {
            get {
                return ResourceManager.GetString("Payment.ExpirationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid expiration date in MM/YYYY format..
        /// </summary>
        public static string Payment_ExpirationValidation {
            get {
                return ResourceManager.GetString("Payment.ExpirationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Design for Bootstrap.
        /// </summary>
        public static string Payment_Title {
            get {
                return ResourceManager.GetString("Payment.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Product_AllFilter {
            get {
                return ResourceManager.GetString("Product.AllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Products.
        /// </summary>
        public static string Product_BackButton {
            get {
                return ResourceManager.GetString("Product.BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Product_DescriptionLabel {
            get {
                return ResourceManager.GetString("Product.DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Product_DetailsButton {
            get {
                return ResourceManager.GetString("Product.DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Category:.
        /// </summary>
        public static string Product_FilterLabel {
            get {
                return ResourceManager.GetString("Product.FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruits.
        /// </summary>
        public static string Product_FruitsFilter {
            get {
                return ResourceManager.GetString("Product.FruitsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products found..
        /// </summary>
        public static string Product_NoProducts {
            get {
                return ResourceManager.GetString("Product.NoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string Product_PriceLabel {
            get {
                return ResourceManager.GetString("Product.PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock:.
        /// </summary>
        public static string Product_StockLabel {
            get {
                return ResourceManager.GetString("Product.StockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetables.
        /// </summary>
        public static string Product_VegetablesFilter {
            get {
                return ResourceManager.GetString("Product.VegetablesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string Profile_BackButton {
            get {
                return ResourceManager.GetString("Profile.BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Profile_EditButton {
            get {
                return ResourceManager.GetString("Profile.EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Profile_EmailLabel {
            get {
                return ResourceManager.GetString("Profile.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string Profile_Header {
            get {
                return ResourceManager.GetString("Profile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Profile_UsernameLabel {
            get {
                return ResourceManager.GetString("Profile.UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Orders.
        /// </summary>
        public static string Profile_ViewOrdersButton {
            get {
                return ResourceManager.GetString("Profile.ViewOrdersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Order.
        /// </summary>
        public static string Shop_AddToOrder {
            get {
                return ResourceManager.GetString("Shop.AddToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse our amazing products.
        /// </summary>
        public static string Shop_Header_Subtitle {
            get {
                return ResourceManager.GetString("Shop.Header.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop in style.
        /// </summary>
        public static string Shop_Header_Title {
            get {
                return ResourceManager.GetString("Shop.Header.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Stock.
        /// </summary>
        public static string Shop_LowStock {
            get {
                return ResourceManager.GetString("Shop.LowStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check back later!.
        /// </summary>
        public static string Shop_NoProducts_Message {
            get {
                return ResourceManager.GetString("Shop.NoProducts.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products available at the moment..
        /// </summary>
        public static string Shop_NoProducts_Title {
            get {
                return ResourceManager.GetString("Shop.NoProducts.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Stock.
        /// </summary>
        public static string Shop_OutOfStock {
            get {
                return ResourceManager.GetString("Shop.OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Stock.
        /// </summary>
        public static string Shop_OutOfStockButton {
            get {
                return ResourceManager.GetString("Shop.OutOfStockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing results for:.
        /// </summary>
        public static string Shop_SearchResults {
            get {
                return ResourceManager.GetString("Shop.SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock:.
        /// </summary>
        public static string Shop_StockLabel {
            get {
                return ResourceManager.GetString("Shop.StockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SignUp_EmailLabel {
            get {
                return ResourceManager.GetString("SignUp.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp_Header {
            get {
                return ResourceManager.GetString("SignUp.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string SignUp_LocationLabel {
            get {
                return ResourceManager.GetString("SignUp.LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SignUp_NameLabel {
            get {
                return ResourceManager.GetString("SignUp.NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignUp_PasswordLabel {
            get {
                return ResourceManager.GetString("SignUp.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string SignUp_PhoneLabel {
            get {
                return ResourceManager.GetString("SignUp.PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SignUp_SubmitButton {
            get {
                return ResourceManager.GetString("SignUp.SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added to order!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
    }
}
